{{ if .Values.dandelion.deployIngress }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cardano-submit-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "submit-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: cardano-submit-api
              servicePort: 8091
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "submit-api.{{ .Values.dandelion.ingressBaseDomain }}"
      #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-graphql-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "graphql-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
                service:
                  name: cardano-graphql
                  port:
                    number: 3100
            path: /
            pathType: Prefix
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "graphql-api.{{ .Values.dandelion.ingressBaseDomain }}"

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chisel-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "chisel-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: chisel-server
              servicePort: 40000
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "chisel-api.{{ .Values.dandelion.ingressBaseDomain }}"
      #secretName: local-tls

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ogmios-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "ogmios-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: ogmios
              servicePort: 1337
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "ogmios-api.{{ .Values.dandelion.ingressBaseDomain }}"
      #secretName: local-tls

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: postgrest-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "postgrest-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: postgrest
              servicePort: 3000
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "postgrest-api.{{ .Values.dandelion.ingressBaseDomain }}"
      #secretName: local-tls

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rosetta-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "rosetta-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: cardano-rosetta
              servicePort: 8080
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "rosetta-api.{{ .Values.dandelion.ingressBaseDomain }}"
      #secretName: local-tls

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: postgresws-api
  namespace: dl-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
spec:
  rules:
    - host: "postgresws-api.{{ .Values.dandelion.ingressBaseDomain }}"
      http:
        paths:
          - backend:
              serviceName: postgres-ws
              servicePort: 3000
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - "postgresws-api.{{ .Values.dandelion.ingressBaseDomain }}"
{{ end }}
