commonLabels:
  environment: dev
  cardano_network: testnet
  cardano_node_type: haskell
  project_name: geniusyield

bases:
- ../../base/common
- ../../base/cardano-node

components:
- ../../base/testnet-patches
