commonLabels:
  environment: dev
  cardano_network: testnet
  cardano_node_type: haskell
  project_name: geniusyield

bases:
- ../testnet-base
- ../../base/helm-charts/postgres-ha
- ../../base/cardano-db-sync
- ../../base/cardano-graphql
- ../../base/cardano-hasura
# - ../../base/cardano-rosetta
# - ../../base/cardano-explorer-api
# - ../../base/cardano-submit-api
#- ../../base/metrics-exporter
# - ../../base/ogmios
- ../../base/postgrest
# - ../../base/koios

resources:
- resources/ingress.yaml

components:
- ../../base/testnet-patches
